#### 1.Set Up

In [161]:
%pip install -q pandas numpy

Note: you may need to restart the kernel to use updated packages.

In [162]:
%pip install --upgrade pip

Requirement already satisfied: pip in .\venv\Lib\site-packages (26.2.1)
Note: you may need to restart the kernel to use updated packages.

In [163]:
import numpy as np
import pandas as pd

pd.set_option("display.max_columns",50)

#### 2.Load the dataset

titanic_dataset.csv

In [164]:
df = pd.read_csv("titanic_dataset.csv")

In [165]:
df.shape

(782, 15)

In [166]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1.0,0.0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1.0,0.0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0.0,0.0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1.0,0.0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0.0,0.0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [167]:
df.shape

(782, 15)

In [168]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 782 entries, 0 to 781
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     782 non-null    int64
 1   pclass       782 non-null    int64
 2   sex          782 non-null    str
 3   age          623 non-null    str
 4   sibsp        781 non-null    float64
 5   parch        781 non-null    float64
 6   fare         781 non-null    float64
 7   embarked     780 non-null    str
 8   class        781 non-null    str
 9   who          781 non-null    str
 10  adult_male   781 non-null    object
 11  deck         180 non-null    str
 12  embark_town  780 non-null    str
 13  alive        781 non-null    str
 14  alone        781 non-null    object
dtypes: float64(3), int64(2), object(2), str(8)
memory usage: 91.8+ KB

In [169]:
df.describe()

         survived      pclass       sibsp       parch        fare
count  782.000000  782.000000  781.000000  781.000000  781.000000
mean     0.388747    2.301790    0.510883    0.372599   33.225095
std      0.487778    0.836719    1.032273    0.802699   52.032466
min      0.000000    1.000000    0.000000    0.000000    0.000000
25%      0.000000    2.000000    0.000000    0.000000    7.925000
50%      0.000000    3.000000    0.000000    0.000000   14.500000
75%      1.000000    3.000000    1.000000    0.000000   31.275000
max      1.000000    3.000000    8.000000    6.000000  512.329200

In [170]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
777,1,3,female,5.0,0.0,0.0,12.4750,S,Third,child,False,NaN,Southampton,yes,True
778,0,3,male,NaN,0.0,0.0,7.7375,Q,Third,man,True,NaN,Queenstown,no,True
779,1,1,female,43.0,0.0,1.0,211.3375,S,First,woman,False,B,Southampton,yes,False
780,1,3,female,13.0,0.0,0.0,7.2292,C,Third,child,False,NaN,Cherbourg,yes,True
781,1,1,female,17... (8 KB left),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 3.Adding few columns for demonstrating data issues

In [171]:
# 1 to 891
np.arange(1,4)

array([1, 2, 3])

In [172]:
len(df)
print(df)

     survived  pclass     sex                age  sibsp  parch      fare  \
0           0       3    male               22.0    1.0    0.0    7.2500
1           1       1  female               38.0    1.0    0.0   71.2833
2           1       3  female               26.0    0.0    0.0    7.9250
3           1       1  female               35.0    1.0    0.0   53.1000
4           0       3    male               35.0    0.0    0.0    8.0500
..        ...     ...     ...                ...    ...    ...       ...
777         1       3  female                5.0    0.0    0.0   12.4750
778         0       3    male                NaN    0.0    0.0    7.7375
779         1       1  female               43.0    0.0    1.0  211.3375
780         1       3  female               13.0    0.0    0.0    7.2292
781         1       1  female  17... (8 KB left)    NaN    NaN       NaN

    embarked  class    who adult_male deck  embark_town alive  alone
0          S  Third    man       True  NaN  Southampton    no  False
1          C  First  woman      False    C    Cherbourg   yes  False
2          S  Third  woman      False  NaN  Southampton   yes   True
3          S  First  woman      False    C  Southampton   yes  False
4          S  Third    man       True  NaN  Southampton    no   True
..       ...    ...    ...        ...  ...          ...   ...    ...
777        S  Third  child      False  NaN  Southampton   yes   True
778        Q  Third    man       True  NaN   Queenstown    no   True
779        S  First  woman      False    B  Southampton   yes  False
780        C  Third  child      False  NaN    Cherbourg   yes   True
781      NaN    NaN    NaN        NaN  NaN          NaN   NaN    NaN

[782 rows x 15 columns]

In [173]:
# np.arange(1,891+1)
np.arange(1,len(df)+1)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
       183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
       196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208,
       209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,
       222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234,
       235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247,
       248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260,
       261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273,
       274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286,
       287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299,
       300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312,
       313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325,
       326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338,
       339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351,
       352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364,
       365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377,
       378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390,
       391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403,
       404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416,
       417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429,
       430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442,
       443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455,
       456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468,
       469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481,
       482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494,
       495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507,
       508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520,
       521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533,
       534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546,
       547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559,
       560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572,
       573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585,
       586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598,
       599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611,
       612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624,
       625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637,
       638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650,
       651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663,
       664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676,
       677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689,
       690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702,
       703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715,
       716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728,
       729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741,
       742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754,
       755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767,
       768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780,
       781, 782])

In [174]:
df["embark_town_dirty"] = df["embark_town"].copy()
sample_idx = df["embark_town_dirty"].dropna().sample(6,random_state=42).index
sample_idx

Index([596, 588, 544, 645, 488, 212], dtype='int64')

In [175]:
df.loc[sample_idx[0:2],"embark_town_dirty"] = df.loc[sample_idx[0:2],"embark_town_dirty"].str.upper()
df.loc[sample_idx[2:4],"embark_town_dirty"] = df.loc[sample_idx[2:4],"embark_town_dirty"].str.strip().apply(lambda x : f" {x} ")
df.loc[sample_idx[4:6],"embark_town_dirty"] = "unknown"

In [176]:
df.iloc[544]["embark_town_dirty"]

' Cherbourg '

In [177]:
df.iloc[645]["embark_town_dirty"]

' Cherbourg '

In [178]:
# ID like columns
df["passenger_id"] = np.arange(1,len(df)+1)

# constant column
df["constant_column"] = 1

# df["embarked_town_dirty"] = df["embark_town"].copy()

# #  select a few random rows (only non-missing)
# sample_idx = df["embarked_town_dirty"].dropna().sample(6,random_state=42).index

# # apply simple dirty transformations
# df.loc[sample_idx[0:2],"embarked_town_dirty"] = df.loc[sample_idx[0:2],"embarked_town_dirty"].str.upper()
# df.loc[sample_idx[2:4],"embarked_town_dirty"] = df.loc[sample_idx[0:2],"embarked_town_dirty"].str.strip().apply(lambda x: f" {x} ")
# df.loc[sample_idx[4:6],"embarked_town_dirty"] = "unknown"

In [179]:
df["embark_town_dirty"].head(782)
df["embark_town_dirty"].isna().sum()
df[df["embark_town_dirty"].isna()]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,embark_town_dirty,passenger_id,constant_column
61,1,1,female,38.0,0.0,0.0,80.0,NaN,First,woman,False,B,NaN,yes,True,NaN,62,1
781,1,1,female,17... (8 KB left),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,782,1

In [180]:
# sample_idx = df["embarked_town_dirty"].dropna().sample(6,random_state=2).index
# print(sample_idx)

In [181]:
# df.loc[sample_idx[0:2], "embarked_town_dirty"] = (
#     df.loc[sample_idx[0:2], "embarked_town_dirty"].str.upper()
# )

# print(df.loc[sample_idx[0:2], ["embarked_town_dirty", "embarked_town_dirty"]])

In [182]:
# df.loc[sample_idx[0:2],"embarked_town_dirty"] = df.loc[sample_idx[0:2],"embarked_town_dirty"].str.strip().apply(lambda x: f" {x} ")
# print(df.loc[sample_idx[0:2], ["embarked_town_dirty", "embarked_town_dirty"]])

In [183]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,embark_town_dirty,passenger_id,constant_column
0,0,3,male,22.0,1.0,0.0,7.2500,S,Third,man,True,NaN,Southampton,no,False,Southampton,1,1
1,1,1,female,38.0,1.0,0.0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,Cherbourg,2,1
2,1,3,female,26.0,0.0,0.0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,Southampton,3,1
3,1,1,female,35.0,1.0,0.0,53.1000,S,First,woman,False,C,Southampton,yes,False,Southampton,4,1
4,0,3,male,35.0,0.0,0.0,8.0500,S,Third,man,True,NaN,Southampton,no,True,Southampton,5,1

In [184]:
df.shape

(782, 18)

In [185]:
df.dtypes

survived               int64
pclass                 int64
sex                      str
age                      str
sibsp                float64
parch                float64
fare                 float64
embarked                 str
class                    str
who                      str
adult_male            object
deck                     str
embark_town              str
alive                    str
alone                 object
embark_town_dirty        str
passenger_id           int64
constant_column        int64
dtype: object

In [186]:
df.info

<bound method DataFrame.info of      survived  pclass     sex                age  sibsp  parch      fare  \
0           0       3    male               22.0    1.0    0.0    7.2500
1           1       1  female               38.0    1.0    0.0   71.2833
2           1       3  female               26.0    0.0    0.0    7.9250
3           1       1  female               35.0    1.0    0.0   53.1000
4           0       3    male               35.0    0.0    0.0    8.0500
..        ...     ...     ...                ...    ...    ...       ...
777         1       3  female                5.0    0.0    0.0   12.4750
778         0       3    male                NaN    0.0    0.0    7.7375
779         1       1  female               43.0    0.0    1.0  211.3375
780         1       3  female               13.0    0.0    0.0    7.2292
781         1       1  female  17... (8 KB left)    NaN    NaN       NaN

    embarked  class    who adult_male deck  embark_town alive  alone  \
0          S  Third    man       True  NaN  Southampton    no  False
1          C  First  woman      False    C    Cherbourg   yes  False
2          S  Third  woman      False  NaN  Southampton   yes   True
3          S  First  woman      False    C  Southampton   yes  False
4          S  Third    man       True  NaN  Southampton    no   True
..       ...    ...    ...        ...  ...          ...   ...    ...
777        S  Third  child      False  NaN  Southampton   yes   True
778        Q  Third    man       True  NaN   Queenstown    no   True
779        S  First  woman      False    B  Southampton   yes  False
780        C  Third  child      False  NaN    Cherbourg   yes   True
781      NaN    NaN    NaN        NaN  NaN          NaN   NaN    NaN

    embark_town_dirty  passenger_id  constant_column
0         Southampton             1                1
1           Cherbourg             2                1
2         Southampton             3                1
3         Southampton             4                1
4         Southampton             5                1
..                ...           ...              ...
777       Southampton           778                1
778        Queenstown           779                1
779       Southampton           780                1
780         Cherbourg           781                1
781               NaN           782                1

[782 rows x 18 columns]>

4.1.Baics DataSetOverView

In [187]:
print(df.shape)
print("-"*50)

(782, 18)
--------------------------------------------------

In [188]:
df.nunique()

survived               2
pclass                 3
sex                    2
age                   86
sibsp                  7
parch                  7
fare                 231
embarked               3
class                  3
who                    3
adult_male             2
deck                   7
embark_town            3
alive                  2
alone                  2
embark_town_dirty      6
passenger_id         782
constant_column        1
dtype: int64

In [189]:
df.describe(include='all')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,embark_town_dirty,passenger_id,constant_column
count,782.000000,782.000000,782,623,781.000000,781.000000,781.000000,780,781,781,781,180,780,781,781,780,782.000000,782.0
unique,NaN,NaN,2,86,NaN,NaN,NaN,3,3,3,2,7,3,2,2,6,NaN,NaN
top,NaN,NaN,male,24.0,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True,Southampton,NaN,NaN
freq,NaN,NaN,504,28,NaN,NaN,NaN,563,427,474,474,55,563,478,468,559,NaN,NaN
mean,0.388747,2.301790,NaN,NaN,0.510883,0.372599,33.225095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,391.500000,1.0
std,0.487778,0.836719,NaN,NaN,1.032273,0.802699,52.032466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,225.888247,0.0
min,0.000000,1.000000,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.0
25%,0.000000,2.000000,NaN,NaN,0.000000,0.000000,7.925000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,196.250000,1.0
50%,0.000000,3.000000,NaN,NaN,0.000000,0.000000,14.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,391.500000,1.0
75%,1.000000,3.000000,NaN,NaN,1.000000,0.000000,31.275000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,586.750000,1.0
max,1.000000,3.000000,NaN,NaN,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,782.000000,1.0

In [190]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,embark_town_dirty,passenger_id,constant_column
0,0,3,male,22.0,1.0,0.0,7.2500,S,Third,man,True,NaN,Southampton,no,False,Southampton,1,1
1,1,1,female,38.0,1.0,0.0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,Cherbourg,2,1
2,1,3,female,26.0,0.0,0.0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,Southampton,3,1
3,1,1,female,35.0,1.0,0.0,53.1000,S,First,woman,False,C,Southampton,yes,False,Southampton,4,1
4,0,3,male,35.0,0.0,0.0,8.0500,S,Third,man,True,NaN,Southampton,no,True,Southampton,5,1

4.2.Missing Values summary

In [191]:
missing_count = df.isna().sum().sort_values(ascending=True)
missing_percent = (df.isna().mean() * 100).sort_values(ascending=False)

missing_summary = pd.DataFrame(
    {
        "missing_count" : missing_count,
        "missing_percent" : missing_percent
    }
)
print("Missing Values Summary")
missing_summary

Missing Values Summary

                   missing_count  missing_percent
adult_male                     1         0.127877
age                          159        20.332481
alive                          1         0.127877
alone                          1         0.127877
class                          1         0.127877
constant_column                0         0.000000
deck                         602        76.982097
embark_town                    2         0.255754
embark_town_dirty              2         0.255754
embarked                       2         0.255754
fare                           1         0.127877
parch                          1         0.127877
passenger_id                   0         0.000000
pclass                         0         0.000000
sex                            0         0.000000
sibsp                          1         0.127877
survived                       0         0.000000
who                            1         0.127877

4.3.Duplicates

In [192]:
duplicates_mask = df.duplicated()
num_duplicates = duplicates_mask.sum()

print("Number of duplicate rows:",num_duplicates)

# for removing duplicates
# df_no_duplicates = df.drop_duplicates()
# df_no_duplicates

Number of duplicate rows: 0

In [193]:
pd.Series([False,True,True,False,False]).sum()

np.int64(2)

**4.4. Data Type Validations**

In [194]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,embark_town_dirty,passenger_id,constant_column
0,0,3,male,22.0,1.0,0.0,7.2500,S,Third,man,True,NaN,Southampton,no,False,Southampton,1,1
1,1,1,female,38.0,1.0,0.0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,Cherbourg,2,1
2,1,3,female,26.0,0.0,0.0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,Southampton,3,1
3,1,1,female,35.0,1.0,0.0,53.1000,S,First,woman,False,C,Southampton,yes,False,Southampton,4,1
4,0,3,male,35.0,0.0,0.0,8.0500,S,Third,man,True,NaN,Southampton,no,True,Southampton,5,1

In [195]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone', 'embark_town_dirty', 'passenger_id',
       'constant_column'],
      dtype='str')

In [196]:
expected_types = {
    "survived" : "int64",
    "pclass" : "int64",
    "sex" : "category",
    "age" : "float64",
    "fare" : "float64",
    "embark_town" :"category",
    "passenger_id" : "int64"
}

for col,expected in expected_types.items():
    print(col,expected)

survived int64
pclass int64
sex category
age float64
fare float64
embark_town category
passenger_id int64

In [197]:
expected_types = {
    "survived" : "int64",
    "pclass" : "int64",
    "sex" : "category",
    "age" : "float64",
    "fare" : "float64",
    "embark_town" :"category",
    "passenger_id" : "int64"
}
print("Data Type Validation:")
for col,expected in expected_types.items():
    if col in df.columns:
        actual = df[col].dtype
        print(f"{col}: actual={actual},expected={expected}")

Data Type Validation:
survived: actual=int64,expected=int64
pclass: actual=int64,expected=int64
sex: actual=str,expected=category
age: actual=str,expected=float64
fare: actual=float64,expected=float64
embark_town: actual=str,expected=category
passenger_id: actual=int64,expected=int64

In [198]:
expected_types

{'survived': 'int64',
 'pclass': 'int64',
 'sex': 'category',
 'age': 'float64',
 'fare': 'float64',
 'embark_town': 'category',
 'passenger_id': 'int64'}

In [199]:
df['survived'].dtype

dtype('int64')

In [200]:
df['pclass'].dtype

dtype('int64')

In [201]:
df['pclass'] = df['pclass'].astype("int64")

In [202]:
df['pclass'].dtype

dtype('int64')

In [203]:
df.nunique()

survived               2
pclass                 3
sex                    2
age                   86
sibsp                  7
parch                  7
fare                 231
embarked               3
class                  3
who                    3
adult_male             2
deck                   7
embark_town            3
alive                  2
alone                  2
embark_town_dirty      6
passenger_id         782
constant_column        1
dtype: int64

**4.5. Constant and Quasi-Constant columns**

In [204]:
n_rows = len(df)
nunique = df.nunique()
constant_cols = nunique[nunique == 1].index.to_list()
print("Constant columns:",constant_cols)


# quasi constant columns
quasi_constant_cols = []
for col in df.columns:
    # top_freq = df[col].value_counts()
    top_freq = df[col].value_counts(normalize=True,dropna=False).values[0]
    # print(top_freq)
    if top_freq > 0.95 and col not in constant_cols:
        quasi_constant_cols.append(col)
print("Quasi constant columns (top value more than 95 percent:)",quasi_constant_cols)

Constant columns: ['constant_column']
Quasi constant columns (top value more than 95 percent:) []

In [205]:
df["constant_column"].value_counts()

constant_column
1    782
Name: count, dtype: int64

In [206]:
df["age"].value_counts()

age
24.0                 28
22.0                 26
19.0                 23
28.0                 22
21.0                 22
                     ..
80.0                  1
24.5                  1
0.67                  1
30.5                  1
17... (8 KB left)     1
Name: count, Length: 86, dtype: int64

In [207]:
# df["survived"].value_counts()
df["survived"].value_counts(normalize=True)

survived
0    0.611253
1    0.388747
Name: proportion, dtype: float64

In [208]:
df["constant_column"]

0      1
1      1
2      1
3      1
4      1
      ..
777    1
778    1
779    1
780    1
781    1
Name: constant_column, Length: 782, dtype: int64

In [209]:
df["constant_column"].value_counts()

constant_column
1    782
Name: count, dtype: int64

In [210]:
df["constant_column"].value_counts(normalize=True)

constant_column
1    1.0
Name: proportion, dtype: float64

**4.6. 1D Like Columns**

Columns where number of unique is closer to number of df rows

In [211]:
n_rows = len(df) 

n_rows
id_like_cols = []
# df.columns
for  col in df.columns:
    if df[col].nunique(dropna=False) == n_rows:
        id_like_cols.append(col)
print("1D like columns:",id_like_cols)

1D like columns: ['passenger_id']

In [212]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone', 'embark_town_dirty', 'passenger_id',
       'constant_column'],
      dtype='str')

In [213]:
df['passenger_id'].nunique(dropna=False) == n_rows

True

In [218]:
object_cols = df.select_dtypes(include=["str"]).columns.to_list()
print(object_cols)

['sex', 'age', 'embarked', 'class', 'who', 'deck', 'embark_town', 'alive', 'embark_town_dirty']

**4.7 String Inconsistencies**

In [219]:
object_cols = df.select_dtypes(include=["str"]).columns.to_list()
print(object_cols)

# simple clean : strip spaces convert it to lower case
df["embark_town_clean"] = (
    df["embark_town_dirty"]
    .astype(str)
    .str.strip()
    .str.lower()
    .replace("unknown",np.nan)
)

['sex', 'age', 'embarked', 'class', 'who', 'deck', 'embark_town', 'alive', 'embark_town_dirty']

In [216]:
df['who'].value_counts()

who
man      474
woman    238
child     69
Name: count, dtype: int64

**4.8.High null columns**

In [ ]:
high_null_threshold = 0.4


high_null_cols = missing_summary[missing_summary["missing_percent"] >= high_null_threshold * 100]

print("Columns with high missing percent")
print(high_null_cols)

Columns with high missing percent
      missing_count  missing_percent
deck            602        76.982097

4.9. High zero columns (numeric)

In [225]:
numeric_cols = df.select_dtypes(include=[np.number]).columns.to_list()
print(numeric_cols)
zero_share = {}
for col in numeric_cols:
    zero_share[col] = (df[col] ==0).mean()

zero_share_series = pd.Series(zero_share).sort_values(ascending=False)
print(zero_share_series)

['survived', 'pclass', 'sibsp', 'parch', 'fare', 'passenger_id', 'constant_column']
parch              0.767263
sibsp              0.676471
survived           0.611253
fare               0.015345
pclass             0.000000
passenger_id       0.000000
constant_column    0.000000
dtype: float64